# Site settings
title: Blawg
email: neil.matatall@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just some ramblings. Probably about CSP.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://oreoshake.github.io" # the base hostname & protocol for your site
twitter_username: ndm
github_username:  oreoshake

# Build settings
markdown: kramdown
highlighter: pygments

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
