name: stats
on:
  push:
  schedule:
  - cron: '0 0 * * *' # Once per day at midnight
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Run script
      run: |
        gem install --no-document octokit
        GITHUB_TOKEN=${{ secrets.PAT }} ruby main.rb
